//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 15.0.26323.1
// 
namespace App5.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IVideoStream")]
    public interface IVideoStream {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVideoStream/StartPreview", ReplyAction="http://tempuri.org/IVideoStream/StartPreviewResponse")]
        System.Threading.Tasks.Task StartPreviewAsync(string number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVideoStream/GetStream", ReplyAction="http://tempuri.org/IVideoStream/GetStreamResponse")]
        System.Threading.Tasks.Task<byte[]> GetStreamAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVideoStream/GetList", ReplyAction="http://tempuri.org/IVideoStream/GetListResponse")]
        System.Threading.Tasks.Task<string[]> GetListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVideoStream/StreamingVideo", ReplyAction="http://tempuri.org/IVideoStream/StreamingVideoResponse")]
        System.Threading.Tasks.Task<byte[]> StreamingVideoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVideoStreamChannel : App5.ServiceReference1.IVideoStream, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VideoStreamClient : System.ServiceModel.ClientBase<App5.ServiceReference1.IVideoStream>, App5.ServiceReference1.IVideoStream {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public VideoStreamClient() : 
                base(VideoStreamClient.GetDefaultBinding(), VideoStreamClient.GetDefaultEndpointAddress()) {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IVideoStream.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VideoStreamClient(EndpointConfiguration endpointConfiguration) : 
                base(VideoStreamClient.GetBindingForEndpoint(endpointConfiguration), VideoStreamClient.GetEndpointAddress(endpointConfiguration)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VideoStreamClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(VideoStreamClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress)) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VideoStreamClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(VideoStreamClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress) {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VideoStreamClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Threading.Tasks.Task StartPreviewAsync(string number) {
            return base.Channel.StartPreviewAsync(number);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetStreamAsync() {
            return base.Channel.GetStreamAsync();
        }
        
        public System.Threading.Tasks.Task<string[]> GetListAsync() {
            return base.Channel.GetListAsync();
        }
        
        public System.Threading.Tasks.Task<byte[]> StreamingVideoAsync() {
            return base.Channel.StreamingVideoAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync() {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IVideoStream)) {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration) {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IVideoStream)) {
                return new System.ServiceModel.EndpointAddress("http://localhost:9000/streamserver");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding() {
            return VideoStreamClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IVideoStream);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress() {
            return VideoStreamClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IVideoStream);
        }
        
        public enum EndpointConfiguration {
            
            BasicHttpBinding_IVideoStream,
        }
    }
}
